
import Database.Star_server;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Sidiq
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public FormUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        btnLogOff.setVisible(false);
        btnFormMobil.setVisible(false);
        btnFormPeminjam.setVisible(false);
        btnFormUser.setVisible(false);
        btnTransaksi.setVisible(false);
        




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFormUser = new usu.widget.ButtonGlass();
        btnTransaksi = new usu.widget.ButtonGlass();
        btnFormPeminjam = new usu.widget.ButtonGlass();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnFormMobil = new usu.widget.ButtonGlass();
        btnLogin = new usu.widget.ButtonGlass();
        btnLogOff = new usu.widget.ButtonGlass();
        btnExit = new usu.widget.ButtonGlass();
        btnInfo = new usu.widget.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Rental Mobil");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFormUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_iconn.png"))); // NOI18N
        btnFormUser.setText("Add User");
        btnFormUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFormUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFormUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 80));

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi.png"))); // NOI18N
        btnTransaksi.setText("Pengembalian Mobil");
        btnTransaksi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, 80));

        btnFormPeminjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pinjam1.png"))); // NOI18N
        btnFormPeminjam.setText("Pinjam Mobil");
        btnFormPeminjam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFormPeminjam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFormPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPeminjamActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 80));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1220, 891));

        btnFormMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_mobil1.png"))); // NOI18N
        btnFormMobil.setText("Add Mobil");
        btnFormMobil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFormMobil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFormMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormMobilActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, 80));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginoke.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 80));

        btnLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log_off copy.png"))); // NOI18N
        btnLogOff.setText("Log Off");
        btnLogOff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOff.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOffActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 80));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit1.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 210, 80));

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info.png"))); // NOI18N
        btnInfo.setText("Informasi");
        btnInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 210, 80));

        jLabel1.setBackground(new java.awt.Color(153, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormUserActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormUser fm = new FormUser();
        fm.setVisible(true);
        jDesktopPane1.add(fm);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormUserActionPerformed

    private void btnFormPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPeminjamActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormPeminjam fm = new FormPeminjam();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_btnFormPeminjamActionPerformed

    private void btnFormMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormMobilActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormMobil fm = new FormMobil();
        fm.setVisible(true);
        jDesktopPane1.add(fm);        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormMobilActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        //     jDesktopPane1.removeAll();
        //     jDesktopPane1.repaint();
        dispose();
        FormLogin fm = new FormLogin();
        fm.setVisible(true);
        //jDesktopPane1.add(fm);


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormPengembalian fm = new FormPengembalian();
        fm.setVisible(true);
        jDesktopPane1.add(fm);// TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOffActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        btnLogin.setVisible(true);
        btnLogOff.setVisible(false);
        btnLogOff.setVisible(false);
        btnFormMobil.setVisible(false);
        btnFormPeminjam.setVisible(false);
        btnFormUser.setVisible(false);
        btnTransaksi.setVisible(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOffActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Informasi a = new Informasi();
        a.setVisible(true);
        jDesktopPane1.add(a);
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    public void admin() {

        btnFormMobil.setVisible(true);
        btnFormPeminjam.setVisible(true);
        btnFormUser.setVisible(true);
        btnLogOff.setVisible(true);
        btnLogin.setVisible(false);
        btnTransaksi.setVisible(true);
        

    }

    public void user() {
        btnFormMobil.setVisible(true);
        btnFormPeminjam.setVisible(true);
        btnFormUser.setVisible(false);
        btnLogOff.setVisible(true);
        btnLogin.setVisible(false);
        btnTransaksi.setVisible(true);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static usu.widget.ButtonGlass btnExit;
    public static usu.widget.ButtonGlass btnFormMobil;
    public static usu.widget.ButtonGlass btnFormPeminjam;
    public static usu.widget.ButtonGlass btnFormUser;
    public static usu.widget.ButtonGlass btnInfo;
    public static usu.widget.ButtonGlass btnLogOff;
    public static usu.widget.ButtonGlass btnLogin;
    public static usu.widget.ButtonGlass btnTransaksi;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
